# 决定插件每游戏刻替换多少垂直单位的方块，每秒更新的方块量 = 此设置的值 * 墙的高度 * 20 (* 即乘以)
# 最少为 1 。无效的值会被静默地忽略并使用 1 为值。
unit-per-tick: 5

# 墙的高度
wall-height: 50

# 最大可撤销步数，若值小于等于 0 ，则认为可无限撤销。
# 警告: 建议限制最大撤销步数，否则你的服务器将面临内存溢出的风险！
max-undo-steps: 30

# 当玩家预定的位置超过这个数时，发出警告，并建议玩家先提交一次。
queue-warn-threshold: 300